application: pittdesignexpo
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail 

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts
  
- url: /stopVoting
  script: pittdesignexpo.app
  login: admin  
- url: /startVoting
  script: pittdesignexpo.app
  login: admin
- url: /clearDB
  script: pittdesignexpo.app
  login: admin
- url: /addPosters
  script: pittdesignexpo.app
  login: admin
- url: /getTrends
  script: pittdesignexpo.app
  login: admin
  
- url: /_ah/mail/.+
  script: pittdesignexpo.app
  login: admin  
  
- url: /.*
  script: pittdesignexpo.app 
  
libraries:
- name: webapp2
  version: "2.5.2"