application: pittdesignexpo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts
  
- url: /getShows
  script: pittdesignexpo.app
  login: admin
- url: /searchShow
  script: pittdesignexpo.app
  login: admin  
- url: /fixPNG
  script: pittdesignexpo.app
  login: admin  
- url: /setcom
  script: pittdesignexpo.app
  login: admin  
  
- url: /.*
  script: pittdesignexpo.app
  
libraries:
- name: webapp2
  version: "2.5.2"