application: teleddiction
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: teleddiction.app
  
libraries:
- name: webapp2
  version: "2.5.2"

